cc_test(
    name = "hello-test",
    srcs = ["hello_test.cc"],
    deps = [
        # "@googletest//:gtest_main",
        "@gtest//:main",
        "//simi:simi",
    ],
    data = [
        "//data:test_data.txt"
    ],
)
