cc_binary(
    name = "how_to_use",
    srcs = ["how_to_use.cc"],
    deps = [
        "//simi:simi",
    ],
    data = [
        "//data:test_data.txt"
    ],
)

cc_binary(
    name = "diff_sample_avg",
    srcs = ["difficulty_sample_avg.cc"],
    deps = [
        "//simi:simi",
    ],
)